apiVersion: eventing.knative.dev/v1alpha1
kind: Channel
metadata:
  name: cj-1
  namespace: default
spec:
  provisioner:
    apiVersion: messaing.knative.dev/v1alpha1
    kind: InMemoryChannel
    name: in-memory-channel
